apiVersion: v1
kind: Secret
metadata:
  name: {{ include "constellation.secretName" . }}
  labels:
    {{- include "constellation.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.constellation.secretEnv }}
  {{- if $value }}
  {{ $key | lower }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}