use std::path::{Path, PathBuf};
use std::fs;
use crate::error::{Error, Result};
use crate::progress::ProgressTracker;
use crate::git::GitManager;
use walkdir::WalkDir;
use regex::Regex;

pub struct InitializerAgent {
    project_path: PathBuf,
    progress_tracker: ProgressTracker,
    git_manager: GitManager,
}

impl InitializerAgent {
    pub fn new(project_path: &Path, high_level_prompt: &str) -> Result<Self> {
        if !project_path.exists() {
            fs::create_dir_all(project_path)?;
        }
        
        let git_manager = if project_path.join(".git").exists() {
            GitManager::open(project_path)?
        } else {
            GitManager::init(project_path)?
        };
        
        let progress_tracker = ProgressTracker::new(project_path)?;
        
        let mut agent = Self {
            project_path: project_path.to_path_buf(),
            progress_tracker,
            git_manager,
        };
        
        agent.initialize_project(high_level_prompt)?;
        
        Ok(agent)
    }

    fn initialize_project(&mut self, high_level_prompt: &str) -> Result<()> {
        self.create_feature_list(high_level_prompt)?;
        self.create_environment_setup()?;
        self.create_progress_file()?;
        self.create_initial_commit()?;
        
        Ok(())
    }

    fn create_feature_list(&mut self, prompt: &str) -> Result<()> {
        let features = self.analyze_prompt_for_features(prompt);
        
        for (name, description) in features {
            self.progress_tracker.add_feature(&name, &description);
        }
        
        let feature_list_path = self.project_path.join("FEATURES.md");
        let mut content = String::new();
        content.push_str("# Project Features\n\n");
        content.push_str(&format!("Generated from: {}\n\n", prompt));
        
        for feature in &self.progress_tracker.progress.features {
            content.push_str(&format!("## {}\n", feature.name));
            content.push_str(&format!("{}\n\n", feature.description));
            content.push_str(&format!("- Status: {:?}\n", feature.status));
            content.push_str(&format!("- ID: {}\n\n", feature.id));
        }
        
        fs::write(feature_list_path, content)?;
        Ok(())
    }

    fn analyze_prompt_for_features(&self, prompt: &str) -> Vec<(String, String)> {
        let mut features = Vec::new();
        
        let feature_patterns = [
            (r"(?i)create\s+(?:a\s+)?(\w+)\s+(?:app|application|system|tool)", "Create application"),
            (r"(?i)implement\s+(?:a\s+)?(\w+)\s+(?:feature|component|module)", "Implement feature"),
            (r"(?i)add\s+(?:a\s+)?(\w+)\s+(?:page|screen|view)", "Add page"),
            (r"(?i)build\s+(?:a\s+)?(\w+)\s+(?:api|endpoint|service)", "Build API"),
            (r"(?i)design\s+(?:a\s+)?(\w+)\s+(?:ui|interface|dashboard)", "Design UI"),
        ];
        
        for (pattern, prefix) in &feature_patterns {
            if let Ok(regex) = Regex::new(pattern) {
                if let Some(captures) = regex.captures(prompt) {
                    if let Some(feature_name) = captures.get(1) {
                        let name = format!("{}: {}", prefix, feature_name.as_str());
                        let description = format!("Implement {} based on prompt: {}", feature_name.as_str(), prompt);
                        features.push((name, description));
                    }
                }
            }
        }
        
        if features.is_empty() {
            features.push((
                "Initial Implementation".to_string(),
                format!("Implement project based on prompt: {}", prompt)
            ));
        }
        
        features
    }

    fn create_environment_setup(&self) -> Result<()> {
        let init_sh_path = self.project_path.join("init.sh");
        let init_sh_content = r#"#!/bin/bash

echo "Setting up project environment..."

# Check for required tools
required_tools=("git" "cargo" "npm" "docker")
for tool in "${required_tools[@]}"; do
    if ! command -v "$tool" &> /dev/null; then
        echo "Warning: $tool is not installed"
    fi
done

# Create basic directory structure
mkdir -p src tests docs config

# Initialize package files if they don't exist
if [ ! -f "Cargo.toml" ]; then
    echo "[package]
name = \"project\"
version = \"0.1.0\"
edition = \"2021\"

[dependencies]
tokio = { version = \"1.48\", features = [\"full\"] }
serde = { version = \"1.0\", features = [\"derive\"] }
anyhow = \"1.0\"
thiserror = \"2.0\"" > Cargo.toml
fi

if [ ! -f "package.json" ]; then
    echo '{
  "name": "project",
  "version": "1.0.0",
  "description": "Project generated by Constellation",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "jest"
  },
  "dependencies": {},
  "devDependencies": {}
}' > package.json
fi

# Create README if it doesn't exist
if [ ! -f "README.md" ]; then
    echo "# Project

Generated by Constellation Agent Harness

## Getting Started

1. Run \`./init.sh\` to set up environment
2. Check \`FEATURES.md\` for project features
3. Follow progress in \`claude-progress.txt\`

## Development

- Features are tracked in \`claude-progress.txt\`
- Each feature should be implemented in its own session
- Commit frequently with descriptive messages
- Test thoroughly before marking features complete" > README.md
fi

echo "Environment setup complete!"
echo "Next steps:"
echo "1. Review FEATURES.md for project scope"
echo "2. Check claude-progress.txt for current status"
echo "3. Start implementing features" > README.md
        "#;
        
        fs::write(init_sh_path, init_sh_content)?;
        
        fs::permissions(&self.project_path.join("init.sh"), 
            fs::Permissions::from_mode(0o755))?;
        
        Ok(())
    }

    fn create_progress_file(&self) -> Result<()> {
        self.progress_tracker.save()?;
        Ok(())
    }

    fn create_initial_commit(&self) -> Result<()> {
        self.git_manager.add_all()?;
        
        let commit_message = format!(
            "Initial commit: Project setup with {} features",
            self.progress_tracker.progress.features.len()
        );
        
        let commit_hash = self.git_manager.commit(
            &commit_message,
            "Constellation Agent",
            "agent@constellation.dev"
        )?;
        
        Ok(())
    }

    pub fn get_project_summary(&self) -> String {
        format!(
            "Project initialized at: {}\nTotal features: {}\nGit repository: {}\nProgress file: claude-progress.txt",
            self.project_path.display(),
            self.progress_tracker.progress.features.len(),
            if self.project_path.join(".git").exists() { "Initialized" } else { "Not initialized" }
        )
    }

    pub fn validate_environment(&self) -> Result<Vec<String>> {
        let mut warnings = Vec::new();
        
        let required_files = ["Cargo.toml", "package.json", "README.md", "FEATURES.md"];
        for file in &required_files {
            if !self.project_path.join(file).exists() {
                warnings.push(format!("Missing file: {}", file));
            }
        }
        
        let git_state = self.git_manager.get_state()?;
        if git_state.has_uncommitted_changes {
            warnings.push("There are uncommitted changes".to_string());
        }
        
        Ok(warnings)
    }
}
