openapi: 3.1.0
info:
  title: Constellation Multi-Agent Platform API
  version: 0.1.0-alpha
  description: API specification for the Constellation agentic platform.
servers:
  - url: http://localhost:8080/v1
    description: Local development server
paths: {}
components:
  schemas: {}